---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pod-identity-webhook
  namespace: pod-identity-webhook
spec:
  secretName: pod-identity-webhook-cert
  commonName: "pod-identity-webhook.pod-identity-webhook.svc.cluster.local"
  dnsNames:
  - "pod-identity-webhook"
  - "pod-identity-webhook.pod-identity-webook"
  - "pod-identity-webhook.pod-identity-webhook.svc"
  - "pod-identity-webhook.pod-identity-webhook.svc.cluster.local"
  isCA: true
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  issuerRef:
    name: kubernetes-ca
    kind: ClusterIssuer

