all:
  vars:
    ansible_user: ec2-user
    ansible_port: 22
    ansible_ssh_private_key_file: "irsa-demo.pem"

control-plane:
  hosts:
    172.23.20.156:
      ansible_host:
      node_pool: control-plane

node:
  hosts:
    172.23.10.36:
      ansible_host:
      node_pool: worker
